# Generated by Django 5.2.11 on 2026-02-24 00:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=20)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
